# Book settings
title:
author: Santiago Castro Dau
logo: docs/images/logo.png

repository:
    url: https://github.com/Sann5/ultra-prot
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://github.com/Sann5/ultra-prot

only_build_toc_files: true
